FROM postgres:15.3-alpine

ENV POSTGRES_DB=shop
ENV POSTGRES_USER=shop
ENV POSTGRES_PASSWORD=shop

# Optional: add init.sql to docker/postgres and uncomment below to run it
# COPY init.sql /docker-entrypoint-initdb.d/init.sql
